LearningSystem.Web/Controllers/CoursesController.cs
namespace LearningSystem.Web.Controllers
{
    using Data.Models;
    using Infrastructure.Extensions;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models.Courses;
    using Service;
    using Service.Models.Courses;
    using System.IO;
    using System.Threading.Tasks;

    using static Core.GlobalConstants;

    public class CoursesController : Controller
    {
        private readonly ICourseService courses;
        private readonly UserManager<User> userManager;

        public CoursesController(
            ICourseService courses,
            UserManager<User> userManager)
        {
            this.courses = courses;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Details(int id)
        {
            var model = new CourseDetailsViewModel();

            var userId = this.userManager.GetUserId(User);


            if (User.Identity.IsAuthenticated)
            {
                model.IsStudentInCourse = await this.courses.IsStudentInCourseAsync(userId, id);
            }

            model.Course = await this.courses.ByIdAsync<CourseDetailsServiceModel>(id);

            if (model.Course == null) return NotFound();

            model.IsTrainer = await this.courses.IsTrainerAsync(userId, id);

            return View(model);
        }

        public async Task<IActionResult> Submission(int courseId, IFormFile exam)
        {
            if (exam == null) return BadRequest();

            if (exam.Length > ExamSubmissionLength
                || !exam.FileName.EndsWith(".zip"))
            {
                this.TempData.AddErrorMessage(@"Invalid operation! File must be in ""zip"" format and less then 2 MB! ");

                return RedirectToAction(nameof(Details), new { id = courseId });
            }

            var studentId = this.userManager.GetUserId(User);

            byte[] examResult;
            using (var memoryStream = new MemoryStream())
            {
                await exam.CopyToAsync(memoryStream);
                examResult = memoryStream.ToArray();
            }

            var success = await this.courses.AddSubmissionAsync(studentId, courseId, examResult);
            if (!success)
            {
                this.TempData.AddErrorMessage("Invalid operation!");

                return RedirectToAction(nameof(Details), new { id = courseId });
            }

            this.TempData.AddSuccessMessage("File added successfully.");

            return RedirectToAction(nameof(Details), new { id = courseId });
        }

        public async Task<IActionResult> SignIn(int courseId)
        {
            var success = await this.courses
                                    .SignInStudentAsync(this.userManager.GetUserId(User), courseId);

            if (!success) return BadRequest();

            this.TempData.AddSuccessMessage($"You joined the course successfully :)");

            return RedirectToAction(nameof(Details), new { id = courseId });
        }

        public async Task<IActionResult> SignOut(int courseId)
        {
            var success = await this.courses.SignOutStudentAsync(this.userManager.GetUserId(User), courseId);

            if (!success) return BadRequest();

            this.TempData.AddErrorMessage($"You are signed out from the course. Sorry to hear that :( ");

            return RedirectToAction(nameof(Details), new { id = courseId });
        }
    }
}

LearningSystem.Web/Controllers/TrainerController.cs
namespace LearningSystem.Web.Controllers
{
    using Data.Models;
    using Infrastructure.Extensions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models.Trainer;
    using Service;
    using Service.Models.Courses;
    using System;
    using System.Threading.Tasks;

    using static Core.GlobalConstants;

    [Authorize(Roles = TrainerRole)]
    public class TrainerController : Controller
    {
        private readonly ITrainerService trainers;
        private readonly UserManager<User> userManager;
        private readonly ICourseService courses;

        public TrainerController(
            ITrainerService trainers,
            UserManager<User> userManager,
            ICourseService courses)
        {
            this.trainers = trainers;
            this.userManager = userManager;
            this.courses = courses;
        }

        public async Task<IActionResult> Courses()
        {
            var userId = this.userManager.GetUserId(User);

            return View(await this.trainers.CoursesAsync(userId));
        }

        public async Task<IActionResult> Students(int courseId, int page = 1)
        {
            var trainerId = this.userManager.GetUserId(User);
            if (!await this.trainers.IsTrainerInCourseAsync(trainerId, courseId)) return BadRequest();

            var course = await this.courses.ByIdAsync<TrainerCourseListingServiceModel>(courseId);
            var students = await this.trainers.StudentsAsync(courseId, page);
            var totalStudentsInCourse = await this.trainers.TotalStudentsAsync(courseId);

            var model = new TrainerCourseWithStudentsViewModel
            {
                CurrentPage = page,
                TotalStudents = totalStudentsInCourse,
                Course = course,
                Students = students
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> GradeStudent(
             string studentId, Grade grade, int courseId, string studentName)
        {
            var trainerId = this.userManager.GetUserId(User);
            if (!await this.trainers.IsTrainerInCourseAsync(trainerId, courseId)) return BadRequest();

            if (String.IsNullOrEmpty(studentId)) return BadRequest();

            var success = await this.trainers.GradeStudentAsync(studentId, grade, courseId);
            if (!success) return BadRequest();

            this.TempData.AddSuccessMessage($"{studentName} grade is now {grade.ToString()}.");

            return RedirectToAction(nameof(Students), new { courseId });
        }

        public async Task<IActionResult> DownloadExam(string studentId, int courseId)
        {
            var userId = this.userManager.GetUserId(User);
            if (!await this.trainers.IsTrainerInCourseAsync(userId, courseId)) return BadRequest();

            var exam = await this.trainers.DownloadExamAsync(studentId, courseId);
            if (exam == null)
            {
                this.TempData.AddErrorMessage("No student exam!");
                return RedirectToAction(nameof(Students), new { courseId, page = 1 });
            }

            var examInfo = await this.trainers.GetNamesAsync(studentId, courseId);

            return File(exam, "application/x-compressed",
                $"{DateTime.UtcNow.ToShortDateString().ToString()}" +
                $"-{examInfo.Username}" +
                $"-{examInfo.CourseName}.zip");
        }
    }
}

LearningSystem.Web/Controllers/UsersController.cs
namespace LearningSystem.Web.Controllers
{
    using Data.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Service;
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    public class UsersController : Controller
    {
        private readonly IUserService users;
        private readonly ICourseService courses;
        private readonly UserManager<User> userManager;

        public UsersController(
            IUserService users,
            ICourseService courses,
            UserManager<User> userManager)
        {
            this.users = users;
            this.courses = courses;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Profile(string username)
        {
            var user = await this.userManager.FindByNameAsync(username);

            var profile = await this.users.ByIdAsync(user.Id);
            if (profile == null) return BadRequest();

            var role = this.userManager.GetRolesAsync(user).Result.FirstOrDefault();
            profile.Role = role;

            return View(profile);
        }

        [Authorize]
        public async Task<IActionResult> Certificate(int courseId)
        {
            var userId = this.userManager.GetUserId(User);
            var courseFriendlyName = await this.courses.GetCourseFriendlyNameAsync(courseId);

            var certificate = await this.users.GetCertificateAsync(courseId, userId);
            if (certificate == null) return BadRequest();

            return File(certificate, "application/pdf",
            $"{courseFriendlyName}-{DateTime.Now:MMMM-dd-yyyy}.pdf");
        }
    }
}

LearningSystem.Web/Views/Shared/_CoursesPartial.cshtml
@model IEnumerable<CourseListingServiceModel>
@{
    var random = new Random();
}

@foreach (var course in Model)
{
    

    <div class="col-md-4">
        <div class="course-content">
            <figure class="course-thumbnail">
                <a asp-controller="Courses" asp-action="Details" asp-route-id="@course.Id">
                    <img src="/images/@(random.Next(1,6)).jpg" alt="">
                </a>
            </figure><!-- .course-thumbnail -->

            <div class="course-content-wrap">
                <header class="entry-header">
                    <h2 class="entry-title">@course.Name</h2>

                    <div class="entry-meta flex align-items-center" style="font-size: 16px !important">
                        <div class="course-author">@course.Trainer</div>

                        <div class="course-date" style="font-size: 14px !important">@course.StartDate.ToString("d") - @course.EndDate.ToString("d")</div>
                    </div><!-- .course-date -->
                </header><!-- .entry-header -->

            </div><!-- .course-content-wrap -->
        </div><!-- .course-content -->
    </div><!-- .col -->
}

LearningSystem.Web/Views/Shared/_Layout.cshtml
@using LearningSystem.Core
@using LearningSystem.Web.Infrastructure
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Learning System</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        
        <!--From Theme-->
        <!-- FontAwesome CSS -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

        <!-- ElegantFonts CSS -->
        <link rel="stylesheet" href="~/css/elegant-fonts.css">

        <!-- themify-icons CSS -->
        <link rel="stylesheet" href="~/css/themify-icons.css">

        <!-- Swiper CSS -->
        <link rel="stylesheet" href="~/css/swiper.min.css">

        <!-- Styles -->
        <link rel="stylesheet" href="~/css/style.css">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        
        <!--From Theme-->
        <!-- FontAwesome CSS -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

        <!-- ElegantFonts CSS -->
        <link rel="stylesheet" href="~/css/elegant-fonts.css">

        <!-- themify-icons CSS -->
        <link rel="stylesheet" href="~/css/themify-icons.css">

        <!-- Swiper CSS -->
        <link rel="stylesheet" href="~/css/swiper.min.css">

        <!-- Styles -->
        <link rel="stylesheet" href="~/css/style.css">
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Learning System</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="Blog" asp-controller="Articles" asp-action="Index">Blog</a></li>
                    @if (User.IsInRole(GlobalConstants.AdministratorRole))
                    {
                        <li><a asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a></li>
                        <li><a asp-area="Admin" asp-controller="Courses" asp-action="Create">Create course</a></li>

                    }
                    @if (User.IsInRole(GlobalConstants.AuthorRole))
                    {
                        <li><a asp-area="Blog" asp-controller="Articles" asp-action="Create">Create article</a></li>
                    }
                    @if (User.IsInRole(GlobalConstants.TrainerRole))
                    {
                        <li><a asp-area="" asp-controller="Trainer" asp-action="Courses">Trainer</a></li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @if (TempData.ContainsKey(GlobalConstants.TempDataSuccessMessageKey))
        {
            <div class="alert alert-success ">
                @TempData[GlobalConstants.TempDataSuccessMessageKey]
            </div>
        }
        @if (TempData.ContainsKey(GlobalConstants.TempDataErrorMessageKey))
        {
            <div class="alert alert-danger">
                @TempData[GlobalConstants.TempDataErrorMessageKey]
            </div>
        }
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Learning System</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>